### ISSUE TITLE
Any Option to scroll Down

### ISSUE THREAD

**Issue by Moussawi7** [souhe/reactScrollbar#11]
Hi,
First thanks for this plugin.
Second, does there are a method so i can scroll to bottom?.
Thank you.

**Comment by souhe** [comment]
I'm glad you like react-scrollbar.

Unfortunatley there is no possibility to scroll down now.  I can(and probably will) add `scrollDown()` and `scrollTop()` methods to the same context object where is `refresh()` method.

**Comment by souhe** [comment]
I've just pushed a release with new methods in `context`
