### ISSUE TITLE
Pull to Refresh

### ISSUE THREAD

**Issue by DylanMerigaud** [souhe/reactScrollbar#113]
Hi,
I've use reactScrollbar to display chat messages, since a chat require the messages to be down to top, I've made the scrollContent absolute in order to make it 100% of the parent width and height.
Works great on desktop, but the problem is that when I use it on mobile I get a warning (from chrome) : `[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093`
wich make it impossible for the user to scroll top because it triggers the Pull to Refresh.
Thx and have great day !

PS: It might be my fault ^^ but from what I understand is that since the eventListener is passive so it doesn't preventDefault.

Here is my scrollContent style: 
```
scrollContent: {
      position: "absolute",
      minWidth: "100%",
      minHeight: "100%",
      justifyContent: "flex-end",
      display: "flex",
      flexDirection: "column",
      alignItems: "center"
    }
```

**Comment by laisooliveira** [comment]
I have the same problem
