### ISSUE TITLE
Performance when using smoothScrolling

### ISSUE THREAD

**Issue by fabian-hiller** [souhe/reactScrollbar#120]
Using **smoothScrolling** causes the component to be **rendered extremely new** while scrolling. This is CPU intensive and can lead to performance issues with larger apps. **Is frequent rendering necessary when scrolling?** If so, is there a way to make **scrolling a bit less smooth** in order to improve performace?

Thank you, Fabian 😃✌️

**Comment by AlexDemzz** [comment]
same issue here :(
