### ISSUE TITLE
Is there a way trigger scrollYTo from outside the ScrollArea component?

### ISSUE THREAD

**Issue by joetidee** [souhe/reactScrollbar#125]
Currently we are limited to being able to run `scrollYTo` from a child component using context. Is there a way to trigger the scrollarea to scroll to a position in the parent of `ScrollArea`?

```
scrollTo(x, y) {
  return {x, y}
}
...
<ScrollArea scrollTo={this.scrollTo}>
  ...
</ScrollArea>
```

**Comment by psychowico** [comment]
you can do it by using React ref mechanism.
e.g.
```jsx
class Component extends React.Component {
  scrollAreaRef = React.createRef();

  onBtnClick= () => {
    this.scrollAreaRef.current.scrollArea.scrollBottom();
  };

  render() {
    ...
    <button onClick={this.onBtnClick}>Scroll now</button>
    <ScrollArea ref={this.scrollAreaRef} ...>
    ...
  }
}
```

be aware that it can make some problems when u trying to scroll a moment after your scroll area change it's size. consider `setTimeout` in such cases.
