### ISSUE TITLE
Touch/Mobile: Screen scrolls with element

### ISSUE THREAD

**Issue by eralston** [souhe/reactScrollbar#127]
When using React-Scrollbar in a page with sufficient height, the scrolling of content within the element causes the window to scroll. I am hoping to understand if this is "as designed" in React-Scrollbar, a side-effect of some CSS trick I should already know, or a legitimate bug in the library.

I've included a zipped video to best describe the issue:
[iOS scrollbar React Video.zip](https://github.com/souhe/reactScrollbar/files/2863314/iOS.scrollbar.React.Video.zip)

This is evident in the demo project if you simply increase the height of the page via CSS past the height of the browser, such as by adding a CSS rule as follows to the /src/scrollArea.less file while the watch is on:

`
body {
    height: 12000px;
}
`
Then try interacting with a browser that uses touch events, such as Chrome on a Windows machine with a touchscreen OR the Blisk browser in their mobile window. It will cause the same issue.

This happens even when "stopScrollPropagation" is set to true. I have not exhaustively tried all scroll behavior CSS modifications.

I hope someone can either point me to a doc explaining what's happening, point out an additional configuration option on the library I should change, a superior library that perhaps solves this issue, or suggestions on how to tell our valued customers that it's a feature not a bug - or all of the above :)

Thank you very much,
Erik Ralston
Chief Architect, LiveTiles

**Comment by souhe** [comment]
Thanks for finding this bug @eralston .

Fixed in v0.5.6 :)

**Comment by eralston** [comment]
Thank you! I'll check it out ASAP 😎👍

**Comment by chtay1** [comment]
I still have this issue after upgrade to v0.5.6
