### ISSUE TITLE
stopScrollPropagation breaking on Chrome 73

### ISSUE THREAD

**Issue by lorinkoz** [souhe/reactScrollbar#128]
Just a notice, on Chrome Versión 73.0.3683.75 `stopScrollPropagation` stopped working. They seem to be introducing some new scrolling features. Can anyone else confirm the bug?

Console displays error: `[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.`

**Comment by souhe** [comment]
Fixed in version v0.5.5
