### ISSUE TITLE
Issue with parent container scrolling

### ISSUE THREAD

**Issue by joetidee** [souhe/reactScrollbar#130]
I made a video of the behaviour when I dynamically add an item the the scrollable area. It appears that the wrapper to the scroll area also scrolls:
https://app.box.com/s/o5goieiaytd4wv5kbeo9xi4f52560srq

**Comment by apenab** [comment]
The solution for this problem is in #129

**Comment by joetidee** [comment]
Do you know when those two commits (since 0.5.4) are going to be released as a new version?

**Comment by apenab** [comment]
@joetidee I have not idea

**Comment by souhe** [comment]
fixed in v0.5.5 :)

**Comment by joetidee** [comment]
This was not fixed in 0.5.6
