### ISSUE TITLE
#129 is not in NPM

### ISSUE THREAD

**Issue by JokerNN** [souhe/reactScrollbar#132]
Hello, thanks for the quick fix of #128! Are there plans to publish the fix to NPM? Thanks

**Comment by johannott** [comment]
Hi, I would also be interested to know if you have a timeline to publish latest changes to npm? Thanks

**Comment by joetidee** [comment]
Any news on when this is going to be published?

**Comment by souhe** [comment]
There is one thing I had to fix before. I'll do it on Monday ;)

**Comment by souhe** [comment]
Done, check outversion v0.5.5
