### ISSUE TITLE
Use transforms instead of margin

### ISSUE THREAD

**Issue by magicspon** [souhe/reactScrollbar#18]
Hello,

I've tried to use css3 transforms instead of margins, but it doesn't work.

Any thoughts? 

Thanks

**Comment by dhmax88** [comment]
+1

**Comment by souhe** [comment]
Hi,

Where do you want to use transforms instead of margins? In some styles or in react-scrollbar code to determine scrollbar position?

**Comment by magicspon** [comment]
Hello,

In the react-scrollbar code.

scrollArea.js
```
var contentStyle = {
            marginTop: this.state.topPosition,
            transform: 'translateX(' + this.state.leftPosition + ')'
};
```

scrollBar.js

```
createScrollStyles(){
    if(this.props.type === 'vertical'){
        return {
            height: this.state.scrollSize,
            marginTop: this.state.position
        };
    } else {
        return {
            width: this.state.scrollSize,
            transform: 'translateX(' + this.state.position + ')'
        };
    }
}
```

nb. I'm only use horizontal scroll

Cheers

**Comment by souhe** [comment]
You should probably add unit to `translateX`.

This works for me:
```javascript
transform: 'translateX(' + this.state.leftPosition + 'px)'
```

**Comment by magicspon** [comment]
doh! 

I can confirm transforms work.

thanks
