### ISSUE TITLE
Warning: require('react/addons') is deprecated. 

### ISSUE THREAD

**Issue by liesislukas** [souhe/reactScrollbar#19]
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.

**Comment by souhe** [comment]
Sorry, I cannot reproduce that. Could yout give me some more details? Which version of react-scrollbar do you use?

**Comment by liesislukas** [comment]
i guess it was different plugin, was testing all what i was able to find. I'm trying to use yours now
