### ISSUE TITLE
scrollBottom && scrollRight position issue

### ISSUE THREAD

**Issue by Moussawi7** [souhe/reactScrollbar#21]
Hi @souhe ,
When i try to scroll to bottom and the content height is smaller than the container height, the content will be pushed down(because ***topPosition*** become positive), so may you want to fix the following:

```javascript
    scrollBottom(){
      if(this.state.realHeight>this.state.containerHeight)
        this.setState({topPosition: -(this.state.realHeight - this.state.containerHeight)});
    }
```
the same for scrollRight.
Thanks.

**Comment by souhe** [comment]
Fixed in version v.0.4.0.

Thanks for notice that issue.
