### ISSUE TITLE
Include dist folder with tags

### ISSUE THREAD

**Issue by polkovnikov-ph** [souhe/reactScrollbar#25]
Why `dist` folder is not included in tags?

**Comment by souhe** [comment]
I don't want to have 'dist' folder in my repo, so I could add it to any future release manually. Is that ok with you?

**Comment by polkovnikov-ph** [comment]
I'd be glad to see any way to load this library from some online code editor like `jsbin`. One of the easiest ways is to make a link directly to a file on `github`. It's hard to do that to `jsx` with dependencies. It would be handy whatever way you choose :)

**Comment by souhe** [comment]
I've just added dist `scrollArea.js` file to latest release.
Sorry for the delay.
