### ISSUE TITLE
Improper handling of mouse events

### ISSUE THREAD

**Issue by polkovnikov-ph** [souhe/reactScrollbar#26]
When the use presses mouse button on a stick and drags it to the content of the scrollable area, the text in the area gets selected.

![image](https://cloud.githubusercontent.com/assets/2983969/12199836/0da63598-b613-11e5-92cd-71df3b4a8223.png)

**Comment by polkovnikov-ph** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/setCapture

**Comment by souhe** [comment]
Hi,
Thanks for finding that issue

**Comment by souhe** [comment]
@polkovnikov-ph  I've just tried to reproduce your issue but I failed. Could you give me some more specific example(some steps to reproduce) or information about environment(which browser) where you are using `scrollArea` component?

**Comment by polkovnikov-ph** [comment]
Reproduces in Firefox 43.0.4 on Windows, doesn't reproduce on Chrome 48 on Windows. Steps:

 - Mousedown on vertical scrollbar;
 - Drag to the left of scrollbar over some text;
 - The text content of scrollable area gets selected.

**Comment by souhe** [comment]
Thanks, you're right.

I'am working mostly on Chrome/Opera so I didn't notice that issue.

**Comment by souhe** [comment]
It's fixed in version v0.4.0 :)
