### ISSUE TITLE
Scroll wheel hits preventDefault if canScrollY is false

### ISSUE THREAD

**Issue by LasseNisted** [souhe/reactScrollbar#31]
If the ScrollArea is big enough to contain contents vertically without scrolling, then the scroll wheel stops working.
It seems handleWheel invokes composeNewState which returns a newState without topPosition defined.
Since this.state.topPosition === 0, then 
if(this.state.topPosition !== newState.topPosition || this.state.leftPosition !== newState.leftPosition){
            e.preventDefault();
}
invokes preventDefault.

Either the newState should have topPosition defined, or its definition should be checked, like:
if (  (r.topPosition && this.state.topPosition!==r.topPosition)||(r.leftPosition && this.state.leftPosition!==r.leftPosition)) {
            e.preventDefault();
}

**Comment by LasseNisted** [comment]
This can be reproduced in the demo: http://souhe.github.io/reactScrollbar/ by setting the scrollarea div to height 600px, resizing the window to have a vertical scrollbar, and then try to scroll.

**Comment by rohanorton** [comment]
Having the same problem

**Comment by souhe** [comment]
You're right. Thanks for noticed that issue.

**Comment by souhe** [comment]
@rohanorton I saw you've made fix for that issue. Would you like to create PR with that fix or should I fix it?

**Comment by rohanorton** [comment]
Of course. I just implemented what @LasseNisted suggested though. Works a charm

**Comment by souhe** [comment]
Thank you both :)
