### ISSUE TITLE
What is the license on this project?

### ISSUE THREAD

**Issue by tkh44** [souhe/reactScrollbar#34]
Just wondering the license of the project.  Could you add one so that others including myself can provide the correct documentation.

You can see how to quickly add a license here: https://help.github.com/articles/open-source-licensing/

Thanks for this great project!

**Comment by souhe** [comment]
It's under MIT license. I've just added LICENSE.md into project and information about it in README.

Thanks for noticed that it's missing.

**Comment by tkh44** [comment]
Thanks!
