### ISSUE TITLE
Added the scrollbar but can't scroll

### ISSUE THREAD

**Issue by asaadmahmoodspin** [souhe/reactScrollbar#36]
I've added the scrollbar but I can't see the scrollbars and neither can I scroll. Using react version 0.14.7
![screen shot 2016-03-22 at 9 04 46 pm](https://cloud.githubusercontent.com/assets/11034289/13958410/c6e958e4-f071-11e5-9812-152bea915ece.png)

**Comment by souhe** [comment]
Hi, 
could you tell more about your configuration(ScrollArea params etc.)?

You can play with working version here: http://jsbin.com/moduteciko/edit?html,js,output

**Comment by asaadmahmoodspin** [comment]
Didn't add any params, was just applying them without it, but wasn't getting the scroll, I think the issue with it was that the `scrollarea area` div was taking the same full height as the inner one.

**Comment by souhe** [comment]
It's probably. You have to set height(px, %, ...) for your ScrollArea element using styles or `className` prop. If not, like you said, `ScrollArea` will take the same height as its content.

**Comment by asaadmahmoodspin** [comment]
Oh Okay, will try it out. Thanks.
