### ISSUE TITLE
Input range bug

### ISSUE THREAD

**Issue by upq** [souhe/reactScrollbar#42]
I noticed that when I Use scroll area all the input type range in the page has a bug were changing the value of any of them keeps it clicked and focused.

How to reproduce?
Just use input range in any view that has this component running.

**Comment by mistermendez** [comment]
I'm also having this exact same issue with input range

**Comment by benkeen** [comment]
Same here.

**Comment by benkeen** [comment]
See PR ^^ for a simple fix for this issue.

**Comment by souhe** [comment]
Fixed by #81
