### ISSUE TITLE
How to know Scroller is at the bottom

### ISSUE THREAD

**Issue by GJ2511** [souhe/reactScrollbar#57]
@souhe 
How to know Scroller is at the bottom ?

**Comment by ImmRanneft** [comment]
Well actually you can pass ``onScroll`` function to handle scrolling, it returns an object

```json
{
    "topPosition": 0,
    "leftPosition": 0,
    "realHeight": 0,
    "containerHeight": 0,
    "realWidth": 0,
    "containerWidth": 0
};
```

Then you should calculate ``realHeight - containerHeight`` and compare the result with ``topPosition``. If it equals - you are at the bottom.
