### ISSUE TITLE
contentStyle property breaks with latest version of dependency react-motion

### ISSUE THREAD

**Issue by sizeight** [souhe/reactScrollbar#59]
See **Upgrading from 0.3.\* to 0.4.0** for react-motion

https://github.com/chenglou/react-motion/wiki#upgrading-from-03-to-040

> Motion's style now only takes values intended to be interpolated. Previously it allowed you to pass {x: spring(0), y: 'randomUnrelatedStuffHere'}. This is now disallowed. Simply pass them to the component you're styling in your children function.

**Comment by alexyaseen** [comment]
I may be running into this as well, not sure if it's the same problem. To replicate, try setting `contentStyle={{ minHeight: '100%' }}`.

**Comment by sizeight** [comment]
@alexyaseen Yes, you are experiencing the same issue. I have fixed the issue and submitted a pull request.

**Comment by alexyaseen** [comment]
@souhe what's involved in getting this pulled in?

**Comment by janejanejane** [comment]
Scrollbar stopped working because of styles not accepting string values like: `{height: 'auto'; width: '100%';}`
