### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by hoosin** [souhe/reactScrollbar#85]
Warning: Tab: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by liesislukas** [comment]
Also

> Warning: Motion: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by AlesJiranek** [comment]
yes, it is necessary to update react-motion package

**Comment by AlesJiranek** [comment]
@souhe hello, are you going to make any changes in this project or you are out of time? I'm asking only because last commit is Dec. 14.

**Comment by microdou** [comment]
@AlesJiranek Looks like the new `react-motion 0.5.0` solved the issue. So a dependency update is needed for `reactScrollbar`.

**Comment by AlesJiranek** [comment]
Yes, I know, that's why I asked

**Comment by sAs59** [comment]
When you gonna fix this issue?

**Comment by hoosin** [comment]
@sAs59 PR https://github.com/souhe/reactScrollbar/pull/86

**Comment by sAs59** [comment]
@hoosin I'm new at GitHub. Could you, please, explain what should I do with this pull request. How can I merge it into reactScrollbar package?

**Comment by souhe** [comment]
Fixed in version 0.5.2. 
I'm really Sorry for the huge delay...
