### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by mishantrop** [souhe/reactScrollbar#93]
With React 15.5, importing PropTypes from React is deprecated in favour of importing from the new 'prop-types' package.

See this link: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by mishantrop** [comment]
Solved in fork: https://github.com/mishantrop/reactScrollbar

**Comment by ebhoren** [comment]
+1

**Comment by erbridge** [comment]
@mishantrop The package published to NPM doesn't have the dist files built.

**Comment by mishantrop** [comment]
@erbridge just run ```gulp production```

**Comment by erbridge** [comment]
@mishantrop Requiring manual builds of a dependency whenever installing or updating it (or rebuilding `node_modules`) isn't really a solution, IMO. It would make more sense for the output of `gulp production` to be what's published to NPM.

**Comment by mishantrop** [comment]
@erbridge ok: https://github.com/mishantrop/reactScrollarea/tree/master/dist

**Comment by souhe** [comment]
Fixed in version 0.5.2
